# fly.toml app configuration file generated for slack-notifier on 2024-02-28T12:07:20-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'slack-notifier'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
